apiVersion: v1
kind: ServiceAccount
metadata:
  name: jenkins
  namespace: dev

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: dev
  name: jenkins-role
rules:
- apiGroups: [""]
  resources: ["pods", "services", "deployments", "persistentvolumeclaims"]
  verbs: ["get", "list", "watch", "create", "delete", "patch", "update"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jenkins-role-binding
  namespace: dev
subjects:
- kind: ServiceAccount
  name: jenkins
  namespace: dev
roleRef:
  kind: Role
  name: jenkins-role
  apiGroup: rbac.authorization.k8s.io
