apiVersion: v1
kind: Secret
metadata:
  name: task-manager-secret
  namespace: dev
type: Opaque
data:
  DB_PASSWORD: cG9zdGdyZXM=
  JWT_SECRET: eW91cl9qd3Rfc2VjcmV0
  PGADMIN_DEFAULT_PASSWORD: eW91cnBhc3N3b3Jk
